# Generated by Django 4.1.1 on 2022-09-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationKey',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=122)),
                ('emailid', models.CharField(max_length=122)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailConfirmationKey',
        ),
    ]
