# Generated by Django 4.1.1 on 2022-09-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_confirmationkey_delete_emailconfirmationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationkey',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
